/**
 * Author:  swendelmann
 * Created: 02.05.2019
 */

CREATE TABLE [LAUFLOG](
	[SCHNITTSTELLE] [varchar](10) NOT NULL,
	[VERSION] [varchar](255) NOT NULL,
	[LAUF] [varchar](10) NOT NULL,
  [UUID] [UNIQUEIDENTIFIER] DEFAULT NEWSEQUENTIALID() NOT NULL,
  [LEVEL] [nvarchar](10) NULL,
	[EVENTDATE] [datetime] NULL,
  [THREAD] [nvarchar](4000) NULL,
  [LOGGER] [nvarchar](1000) NULL,
	[TEXT] [nvarchar](max) NULL,
 CONSTRAINT [PK_LAUFLOG] PRIMARY KEY CLUSTERED 
(
	[SCHNITTSTELLE] ASC,
	[VERSION] ASC,
	[LAUF] ASC,
  [UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]